% EP: extracellular potential [1001 x 1]
% times: [1 x 1001]
% d: distance from axon (default=0.01)
% plotOn: set 1 to plot figure 
function [EP2,times2,AP2]=generate_EP(d,plotOn,Axontype)
    if nargin<3
        Axontype=1; % default
    end
    %----------load AP (by Arancibia-Carcamo model)
    root=fileparts(mfilename("fullpath"));
    % The AP.mat is generated by \MyelinatedAxonModel\StartAxonGUI.m
    switch Axontype
        case 1 % default
           load(fullfile(root,'MyelinatedAxonModel','EP','AP.mat'));
        case 2 % Carcamo2017OpticNerveAxon
           load(fullfile(root,'MyelinatedAxonModel','EP','AP2.mat'));
    end        
    %figure; plot(TIME_VECTOR,MEMBRANE_POTENTIAL);
    %----------------------------------------------------
    idx=21; %15:21; % pick up one from APs
    times=TIME_VECTOR;
    padding=1000;
    dt=times(2)-times(1);
    times=[times,times(end)+(1:padding)*dt]; % add 1000 points of zero
    v=[MEMBRANE_POTENTIAL(:,idx);ones(padding,1)*MEMBRANE_POTENTIAL(end,idx)]; % add 1000 points of zero
    dv=[diff(v);zeros(1,length(idx))]; % 1st derivative of AP
    ddv=[diff(dv);zeros(1,length(idx))]; % 2nd derivative of AP
    %---------calculate extracellular potential------------
    if nargin<1
       d=0.01;
    end
    EP=zeros(size(ddv));
    for i=1:size(v,2)
      for t=1:length(times)
          mask=1./sqrt((times-times(t)).^2+d^2)';
          EP(t,i)=sum(ddv(:,i).*mask);
      end
    end
    %----------------------------------------------------
    if nargin<2
        plotOn=0;
    end
    if plotOn
        figure;
        subplot(411);plot(times,v);ylabel('mV');title({'action potential by AC model','V'})
        subplot(412);plot(times,dv);title('V''')
        subplot(413);plot(times,ddv);title('V''''')
        subplot(414);plot(times,EP);title(sprintf('extracellular potential (d=%g)',d))
        xlabel('time (ms)')
        set(gcf,'position',[0 0 400 600])
    end
    %---------------prepare output data---------------
    dt2=1e-3;
    
    times2=-0.5:dt2:0.5;
    AP2=v-min(v); 
    [val,i]=max(AP2); 
    AP2=AP2/val;
    AP2=interp1(times-times(i),AP2,times2)';
    
    [val,i]=min(EP); 
    EP2=EP/abs(val);
    EP2=interp1(times-times(i),EP2,times2)';
end
