% EP: extracellular potential [1001 x 1]
% times: [1 x 1001]
% d: distance from axon (default=0.01)
% plotOn: set 1 to plot figure 
function [EP,times]=generate_EP(d,plotOn)
    %----------load AP (by Arancibia-Carcamo model)
    % The AP.mat is generated by
    % D:\_3_MPI\meeting\20230220_MEP\MyelinatedAxonModel-master\MyelinatedAxonModel\StartAxonGUI.m
    load('D:\_3_MPI\meeting\20230220_MEP\MyelinatedAxonModel-master\result_vincent\AP.mat');
    %figure; plot(TIME_VECTOR,MEMBRANE_POTENTIAL);
    %----------------------------------------------------
    idx=21;%15:21; % pick up one from APs
    times=TIME_VECTOR;
    v=MEMBRANE_POTENTIAL(:,idx);
    dv=[diff(v);zeros(1,length(idx))]; % 1st derivative of AP
    ddv=[diff(dv);zeros(1,length(idx))]; % 2nd derivative of AP
    %---------calculate extracellular potential------------
    if argin<1
       d=0.01;
    end
    EP=zeros(size(ddv));
    for i=1:size(v,2)
      for t=1:length(times)
          mask=1./sqrt((times-times(t)).^2+d^2)';
          EP(t,i)=sum(ddv(:,i).*mask);
      end
    end
    %----------------------------------------------------
    if argin<2
        plotOn=0;
    end
    if plotOn
        figure;
        subplot(411);plot(times,v);ylabel('mV');title({'action potential by AC model','V'})
        subplot(412);plot(times,dv);title('V''')
        subplot(413);plot(times,ddv);title('V''''')
        subplot(414);plot(times,EP);title(sprintf('extracellular potential (d=%g)',d))
        xlabel('time (ms)')
        set(gcf,'position',[0 0 400 600])
    end
end
